device: cuda

model:
  name: custom_resnet18
  weights: null

  input_channels: 1

  conv1:
    out_channels: 64
    kernel_size: 3
    stride: 1
    padding: 1
    bias: false

  maxpool: identity

  dropout: 0.4
  num_classes: 10

loss:
  name: CrossEntropyLoss

optimizer:
  name: AdamW
  lr: 0.003
  betas:
    - 0.9
    - 0.99
  weight_decay: 0.05

training:
  epochs: 100

  early_stopping:
    enabled: true
    patience: 7
  
  checkpoint_path: src/checkpoints/model.pt
